/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Launch;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Administrador
 */
public class Interfaz extends javax.swing.JFrame {
   
    int Glob_Fas;
    int Glob_Escenarios;
    int Glob_Pob_Inic;
    int Glob_Pob_Limit;
    int Glob_Meta;
    int Glob_NCorridas;
    int Glob_Nucleos;
    
    int Inic_MutaInsert;
    int Inic_NCruza;
    int Inic_TipoHijo;
    int Inic_CMut_Hijos;
    int Inic_CMut_Strg;
    int Inic_TBloqGap;
    int Inic_NumStrg;
    int Inic_Strg_sino;
    
    
    int Shake_TipoHijo;
    int Shake_CMutHijo;
    int Shake_CMutStr;
    int Shake_NCruza;
    int Shake_TBloqGap;
    int Shake_MutaInsert;
    int Shake_Strg_sino;
    int Shake_NumStrg;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
                    initComponents();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        t_Gob_fas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_Glob_Escenarios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_Glob_meta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        t_inic_tipoHijo = new javax.swing.JTextField();
        t_inic_Ncruza = new javax.swing.JTextField();
        t_inic_mutaInsert = new javax.swing.JTextField();
        b_inic_strg = new javax.swing.JToggleButton();
        t_inic_CMutStr = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_inic_TBloqGap = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        t_inic_NumStrg = new javax.swing.JTextField();
        t_sh_NumStrg = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        t_Sh_TBloqGap = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        b_Sh_Str = new javax.swing.JToggleButton();
        jLabel21 = new javax.swing.JLabel();
        t_Sh_MutaInsert = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        t_Sh_NCruza = new javax.swing.JTextField();
        t_Sh_CMutStr = new javax.swing.JTextField();
        t_Sh_CMutHijo = new javax.swing.JTextField();
        t_Sh_TipoHijo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        b_Run = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t_inic_CMutHijos = new javax.swing.JTextField();
        t_Globl_pobinic = new javax.swing.JTextField();
        t_Glob_genctrl = new javax.swing.JTextField();
        t_Glob_NCorridas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t_Glob_Nucleos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        jTextField11.setText("0");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel16.setText("C. Mut. Hijos");

        jTextField24.setText("0");
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        t_Gob_fas.setText("100");
        t_Gob_fas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Gob_fasActionPerformed(evt);
            }
        });

        jLabel9.setText("Fas");

        t_Glob_Escenarios.setText("0");
        t_Glob_Escenarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Glob_EscenariosActionPerformed(evt);
            }
        });

        jLabel6.setText("Escenarios");

        t_Glob_meta.setText("0");
        t_Glob_meta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Glob_metaActionPerformed(evt);
            }
        });
        t_Glob_meta.getAccessibleContext().setAccessibleName("txtMeta");

        jLabel4.setText("x-Meta");

        jLabel10.setText("x-Tipo Hijo");

        jLabel12.setText("x-MutaInsert");

        jLabel28.setText("N. Cruza");

        t_inic_tipoHijo.setText("3");
        t_inic_tipoHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_inic_tipoHijoActionPerformed(evt);
            }
        });

        t_inic_Ncruza.setText("1");
        t_inic_Ncruza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_inic_NcruzaActionPerformed(evt);
            }
        });

        t_inic_mutaInsert.setText("0");
        t_inic_mutaInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_inic_mutaInsertActionPerformed(evt);
            }
        });

        b_inic_strg.setSelected(true);
        b_inic_strg.setText("Strangers");

        t_inic_CMutStr.setText("0");
        t_inic_CMutStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_inic_CMutStrActionPerformed(evt);
            }
        });

        jLabel17.setText("C. Mut. Strg");

        t_inic_TBloqGap.setText("0");
        t_inic_TBloqGap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_inic_TBloqGapActionPerformed(evt);
            }
        });

        jLabel18.setText("T. Bloq. PD");

        jLabel27.setText("Num. Strg");

        t_inic_NumStrg.setText("0");
        t_inic_NumStrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_inic_NumStrgActionPerformed(evt);
            }
        });

        t_sh_NumStrg.setText("25");
        t_sh_NumStrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_sh_NumStrgActionPerformed(evt);
            }
        });

        jLabel29.setText("Num. Strg");

        t_Sh_TBloqGap.setText("4");
        t_Sh_TBloqGap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Sh_TBloqGapActionPerformed(evt);
            }
        });

        jLabel19.setText("C. Mut. Strg");

        jLabel20.setText("T. Bloq. Gap");

        b_Sh_Str.setSelected(true);
        b_Sh_Str.setText("Strangers");

        jLabel21.setText("x-MutaInsert");

        t_Sh_MutaInsert.setText("5");
        t_Sh_MutaInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Sh_MutaInsertActionPerformed(evt);
            }
        });

        jLabel23.setText("x-Tipo Hijo");

        jLabel24.setText("C. Mut. Hijo");

        jLabel25.setText("N. Cruza");

        jLabel26.setText("Shake");

        t_Sh_NCruza.setText("5");
        t_Sh_NCruza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Sh_NCruzaActionPerformed(evt);
            }
        });

        t_Sh_CMutStr.setText("50");
        t_Sh_CMutStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Sh_CMutStrActionPerformed(evt);
            }
        });

        t_Sh_CMutHijo.setText("4");
        t_Sh_CMutHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Sh_CMutHijoActionPerformed(evt);
            }
        });

        t_Sh_TipoHijo.setText("3");
        t_Sh_TipoHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Sh_TipoHijoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("AG1 - 1N1C");

        b_Run.setText("Run");
        b_Run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_RunMouseClicked(evt);
            }
        });
        b_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_RunActionPerformed(evt);
            }
        });

        jLabel7.setText("Pob. Inicial");

        jLabel8.setText("Pob. Limit");

        jLabel15.setText("Nm Value");

        t_inic_CMutHijos.setText("1");
        t_inic_CMutHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_inic_CMutHijosActionPerformed(evt);
            }
        });

        t_Globl_pobinic.setText("500");
        t_Globl_pobinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Globl_pobinicActionPerformed(evt);
            }
        });

        t_Glob_genctrl.setText("100");
        t_Glob_genctrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Glob_genctrlActionPerformed(evt);
            }
        });

        t_Glob_NCorridas.setText("5");
        t_Glob_NCorridas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Glob_NCorridasActionPerformed(evt);
            }
        });

        jLabel13.setText("N. Corridas");

        t_Glob_Nucleos.setText("1");
        t_Glob_Nucleos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Glob_NucleosActionPerformed(evt);
            }
        });

        jLabel14.setText("Nc Value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_Globl_pobinic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_Glob_genctrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_Glob_NCorridas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t_inic_CMutHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(16, 16, 16)
                                        .addComponent(t_Glob_Nucleos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(b_Run)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t_Globl_pobinic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(t_inic_CMutHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t_Glob_genctrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t_Glob_Nucleos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_Glob_NCorridas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_Run))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        b_Run.getAccessibleContext().setAccessibleName("btnRun");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_Glob_metaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Glob_metaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Glob_metaActionPerformed

    private void b_RunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_RunMouseClicked
     Inic_Strg_sino =0;
     Shake_Strg_sino = 0;

     
    this.Glob_Meta = Integer.parseInt(this.t_Glob_meta.getText());
    this.Glob_Fas = Integer.parseInt(this.t_Gob_fas.getText());
    this.Glob_Escenarios = Integer.parseInt(this.t_Glob_Escenarios.getText());
    this.Glob_Pob_Inic = Integer.parseInt(this.t_Globl_pobinic.getText());
    this.Glob_Pob_Limit = Integer.parseInt(this.t_Glob_genctrl.getText());
    this.Glob_NCorridas = Integer.parseInt(this.t_Glob_NCorridas.getText());
    this.Glob_Nucleos = Integer.parseInt(this.t_Glob_Nucleos.getText());

    
    this.Inic_MutaInsert = Integer.parseInt(this.t_inic_mutaInsert.getText());
    this.Inic_NCruza = Integer.parseInt(this.t_inic_Ncruza.getText());
    this.Inic_TipoHijo = Integer.parseInt(this.t_inic_tipoHijo.getText());
    this.Inic_CMut_Hijos = Integer.parseInt(this.t_inic_CMutHijos.getText());
    this.Inic_CMut_Strg = Integer.parseInt(this.t_inic_CMutStr.getText());
    this.Inic_TBloqGap = Integer.parseInt(this.t_inic_TBloqGap.getText());
    this.Inic_NumStrg = Integer.parseInt(this.t_inic_NumStrg.getText());
    if (this.b_inic_strg.isSelected()== true) {
        this.Inic_Strg_sino = 1;}
   
    
    this.Shake_TipoHijo = Integer.parseInt(this.t_Sh_TipoHijo.getText());
    this.Shake_CMutHijo = Integer.parseInt(this.t_Sh_CMutHijo.getText());
    this.Shake_CMutStr = Integer.parseInt(this.t_Sh_CMutStr.getText());
    this.Shake_NCruza = Integer.parseInt(this.t_Sh_NCruza.getText());
    this.Shake_TBloqGap = Integer.parseInt(this.t_Sh_TBloqGap.getText());
    this.Shake_MutaInsert = Integer.parseInt(this.t_Sh_MutaInsert.getText());
    this.Shake_NumStrg = Integer.parseInt(this.t_sh_NumStrg.getText());
    if (this.b_Sh_Str.isSelected()== true) {
        this.Shake_Strg_sino = 1;}
         
         
         
         
         
         
         
         
         Inicio Inicio = new Inicio();
       try {
           Inicio.Iniciar(this);//Ejecuta el ciclo principal enviando parametros en -this
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
       } catch (InterruptedException ex) {
           Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
       } catch (CloneNotSupportedException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
         
       
       
       
    }//GEN-LAST:event_b_RunMouseClicked

    private void b_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_RunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_RunActionPerformed

    private void t_inic_CMutHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_inic_CMutHijosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inic_CMutHijosActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void t_inic_CMutStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_inic_CMutStrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inic_CMutStrActionPerformed

    private void t_inic_TBloqGapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_inic_TBloqGapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inic_TBloqGapActionPerformed

    private void t_Sh_TBloqGapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Sh_TBloqGapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Sh_TBloqGapActionPerformed

    private void t_Sh_MutaInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Sh_MutaInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Sh_MutaInsertActionPerformed

    private void t_inic_NumStrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_inic_NumStrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inic_NumStrgActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void t_inic_tipoHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_inic_tipoHijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inic_tipoHijoActionPerformed

    private void t_inic_NcruzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_inic_NcruzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inic_NcruzaActionPerformed

    private void t_Sh_NCruzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Sh_NCruzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Sh_NCruzaActionPerformed

    private void t_Globl_pobinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Globl_pobinicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Globl_pobinicActionPerformed

    private void t_Sh_CMutStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Sh_CMutStrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Sh_CMutStrActionPerformed

    private void t_Glob_EscenariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Glob_EscenariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Glob_EscenariosActionPerformed

    private void t_Sh_CMutHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Sh_CMutHijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Sh_CMutHijoActionPerformed

    private void t_Glob_genctrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Glob_genctrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Glob_genctrlActionPerformed

    private void t_Sh_TipoHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Sh_TipoHijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Sh_TipoHijoActionPerformed

    private void t_Gob_fasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Gob_fasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Gob_fasActionPerformed

    private void t_sh_NumStrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_sh_NumStrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_sh_NumStrgActionPerformed

    private void t_Glob_NCorridasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Glob_NCorridasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Glob_NCorridasActionPerformed

    private void t_inic_mutaInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_inic_mutaInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_inic_mutaInsertActionPerformed

    private void t_Glob_NucleosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Glob_NucleosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_Glob_NucleosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Run;
    private javax.swing.JToggleButton b_Sh_Str;
    private javax.swing.JToggleButton b_inic_strg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField t_Glob_Escenarios;
    private javax.swing.JTextField t_Glob_NCorridas;
    private javax.swing.JTextField t_Glob_Nucleos;
    private javax.swing.JTextField t_Glob_genctrl;
    private javax.swing.JTextField t_Glob_meta;
    private javax.swing.JTextField t_Globl_pobinic;
    private javax.swing.JTextField t_Gob_fas;
    private javax.swing.JTextField t_Sh_CMutHijo;
    private javax.swing.JTextField t_Sh_CMutStr;
    private javax.swing.JTextField t_Sh_MutaInsert;
    private javax.swing.JTextField t_Sh_NCruza;
    private javax.swing.JTextField t_Sh_TBloqGap;
    private javax.swing.JTextField t_Sh_TipoHijo;
    private javax.swing.JTextField t_inic_CMutHijos;
    private javax.swing.JTextField t_inic_CMutStr;
    private javax.swing.JTextField t_inic_Ncruza;
    private javax.swing.JTextField t_inic_NumStrg;
    private javax.swing.JTextField t_inic_TBloqGap;
    private javax.swing.JTextField t_inic_mutaInsert;
    private javax.swing.JTextField t_inic_tipoHijo;
    private javax.swing.JTextField t_sh_NumStrg;
    // End of variables declaration//GEN-END:variables
}
